CFLAGS	:=	$(BASEFLAGS) $(ARM7FLAGS)
ASFLAGS :=	$(ARM7FLAGS)
VPATH	:=	$(ARM7_VPATH)
DEPSDIR	:=	$(DEPENDS)/arm7

$(LIBDIR)/libnds7.a:	$(ARM7OBJS)

-include $(DEVKITARM)/base_rules
-include $(DEPSDIR)/*.d
