CFLAGS	:=	$(BASEFLAGS) $(ARM9FLAGS)
ASFLAGS :=	$(ARM9FLAGS)
VPATH	:=	$(ARM9_VPATH)
DEPSDIR	:=	$(DEPENDS)/arm9

$(LIBDIR)/libnds9.a:	$(ARM9OBJS)

-include $(DEVKITARM)/base_rules
-include $(DEPSDIR)/*.d

%.o	:	%.bin
	@echo $(notdir $<)
	@$(bin2o)
